### ISSUE TITLE
picat > 3_jugs_mip.pi doesn't work

### ISSUE THREAD

**Issue by dougedmunds** [hakank/hakank#19]
Error message 

GLPSOL--GLPK LP/MIP Solver 5.0
Parameter(s) specified in the command line:
 --cpxlp -o __tmp.sol __tmp.lp
Reading problem data from '__tmp.lp'...
__tmp.lp:28: multiple use of variable 'X2' not allowed
CPLEX LP file processing error
*** error(failed,main/0)

**Comment by hakank** [comment]
Thanks, Doug. 

I report this further to Neng-Fa.

**Comment by hakank** [comment]
Neng-Fa has fixed this issue in the new version 3.6#8 (http://picat-lang.org/download.html ).
