### ISSUE TITLE
spp.mzn loop bug

### ISSUE THREAD

**Issue by lteu** [hakank/hakank#2]
spp.mzn when applying to indirect graph may generate graph loops.

e.g. 1->2, 2->1 may present in the same time in a result.

**Comment by hakank** [comment]
Hi Tony.

Thanks for your comment. Well, this model assume that the graph is directed so I'm not that surprised that cyclic graphs generates problem.:
"""
% Given a directed graph G = (V,E), its edge lengths c(i,j) for all 
% ....
"""

I tested a completely another approach in the MiniZInc model shortest_path_graph.mzn (just pushed to the repo) which seems to handle undirected graphs better. It's just a simple variant of the 3_jugs problem.

/Hakan

**Comment by lteu** [comment]
Indeed! Thanks a lot for your kind suggestion about shortest_path_graph.mzn . That is exactly what I was interested in!
