### ISSUE TITLE
the sicstus examples does not work in sicstus prolog 4.0 and below

### ISSUE THREAD

**Issue by zuloloxi** [hakank/hakank#3]
Hello,
The examples, from **sisctus** folder, does not work in **sicstus prolog 4.0** **and below**,  because the new feature foreach ... param ... was added in sicstus prolog 4.1.
Best regards !

**Comment by hakank** [comment]
Hi  zuloloxi.

Thanks for your comment. 

The loops in SICStus Prolog version 4.1 was actually one main reason that I started to port my constraint programming models to SICStus Prolog. (It's the same reason that I have ported the constraint models to EcLiPse Prolog and B-Prolog: that they supported some kind of explicit for loops.)

The version dependency is mentioned in the index.html file (i.e. http://hakank.org/sicstus/index.html ) but I will add it to a README.md file as well.

Best,

Hakan

**Comment by zuloloxi** [comment]
Hello Hakan,

Do you have an example with foreach ... param ... do, the sicstus prolog 4.1 feature like, that works in 4.0, or how to implement the  "foreach ... param ... do" to work in sicstus prolog 4.0. 

Thanks in advance !

All the best !

Zulo

**Comment by hakank** [comment]
Hi Zulo.

The best place to ask how to implement foreach loops in earlier versions of SICStus Prolog is its Google group: https://groups.google.com/a/sics.se/forum/#!forum/sicstus-users

Best,

Hakan
