### ISSUE TITLE
stable marriage problem

### ISSUE THREAD

**Issue by jburse** [hakank/hakank#6]
Was using your resources (Tom Cruise on an Island):
http://www.hakank.org/eclipse/assignment.ecl

Then saw that the original table reads differently:

![60550224-d3d05d00-9d16-11e9-8681-19f395e797fd](https://user-images.githubusercontent.com/5411487/60551244-f9676180-9d2a-11e9-8234-1786fa381aa5.png)

You got a row in your examples:

`[](7, 8, 8, 4),`
                        
But it should be:

`[](7, 8, 9, 4),`

**Comment by jburse** [comment]
Do you also have some were a log of runs of these models,
what they produce? With this little change the number of solutions
goes from 2 to 3. But I don't know whether what my system

produces matches what other systems produce:

![marriage_jekejeke](https://user-images.githubusercontent.com/5411487/60551303-392e4900-9d2b-11e9-9a2d-cd7cdb572afa.png)

**Comment by hakank** [comment]
Celetrity Assignment problem: Great finding, Jan. It was an error that have propagated from other models. I hope I have updated all the wrong models now.

**Comment by hakank** [comment]
Sorry, I don't have a result log of running all the models (quite a few of the models generates a huge number of solutions).

Here's the output of my Picat model http://hakank.org/picat/assignment.pi  ,.The go2/0 predicate first search for the optimal value and then generates all the optimal solutions. The Celebrity problem (#4) has 3 solutions, just as your model, it's not in the same representation as your model

```
Problem 1
minimize
z = 11
[[2,1,3,5]]

Problem 2
minimize
z = 207
[[3,4,1,2]]

Problem 3
minimize
z = 181
[[3,6,5,7],[3,5,6,7],[3,5,1,7]]

Problem 4
maximize
z = 30
[[3,2,4,1],[1,3,4,2],[1,2,4,3]]

Problem 5
minimize
z = 8
[[2,1,4,5,3]]

Problem 6
minimize
z = 76
[[1,8,7,5,2,6,4,3]]
```

Hope this helps.

**Comment by hakank** [comment]
Oh, I forgot. The Celebrity assignment problem (and model) is not really a stable marriage problem, it's just an assignment problem. See for example http://hakank.org/eclipse/stable_marriage.ecl (or http://hakank.org/common_cp_models/#stablemarriage for some more implementations).

**Comment by jburse** [comment]
Thanks for the hint that it is not stable marriage. Wasn't paying attention.
