### ISSUE TITLE
whats the type of license here

### ISSUE THREAD

**Issue by jburse** [hakank/hakank#7]
Hi Hakan,

I very much like your code. It makes for example good use of Prolog 
comments. But I am little bit at loss. What is the license of all that? 

Best Regards

**Comment by hakank** [comment]
Hi Jan.

Thanks for your kind words. 

Regarding the license it's a good question. To be honest, I'm not exactly sure what license it is: Everyone - and that includes commercial use - are free to use any of the programs/models, though I would prefer that they keep the signature comments such as
```
Model created by Hakan Kjellerstrand, hakank@gmail.com
See also my SWI Prolog page: http://www.hakank.org/swi_prolog/
```

Do you know what kind of license this is?

Best,

Hakan

**Comment by jburse** [comment]
He maybe you could choose one from here,
scroll down on this page:

The Licenses
https://creativecommons.org/licenses/?lang=en

**Comment by hakank** [comment]
Thanks. 

I'll read more about it. Right now I tend towards the Attribution/CC BY. 
Though I still think it's a bit too formal, but perhaps that's just the point of a license.

Informally: you can to whatever you want with a program as long as you credit me.

**Comment by jburse** [comment]
People don't use CC BY always, for example I find:

<package id="chat80" name="Chat-80 Data Files"
     copyright="Copyright (C) 1982 David Warren and Fernando Pereira"
     license="This program may be used, copied, altered or included in other 
                     programs only for academic purposes and provided that the 
                     authorship of the initial program is acknowledged.  
                     Use for commercial purposes without the previous 
                     written agreement of the authors is forbidden."
     author="David Warren and Fernando Pereira"
     webpage="http://www.cis.upenn.edu/~pereira/oldies.html"
     unzip="1"
     />

**Comment by hakank** [comment]
Well, that was written in 1982. I'd better use a modern license...

Until then, you can do whatever you want with the programs with some credit to the author (i.e. me).

**Comment by hakank** [comment]
Well, I decided to go with the MIT license as shown in the  LICENSE file. Does this help you?

**Comment by jburse** [comment]
Hi, I am still learning about licenses. This web site also provides texts:
http://rightsstatements.org/vocab/InC-NC/1.0/

Use by some libraries it seems...
